version: '3.8'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    # Override entrypoint for shell access
    entrypoint: /bin/bash
    tty: true
    stdin_open: true